version: '3.7'

volumes:
    logs:
        driver: local

services:
    backend:
        image: php:8-alpine
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            docker: "true"
        ports:
            - "8080:8080"

#services:
#    backend:
#        image: php:8-alpine
#        working_dir: /var/www/backend
#        command: php -S 0.0.0.0:8080 -t public
#        environment:
#            docker: "true"
#        ports:
#            - "8080:8080"
#        volumes:
#            - .:/var/www
#            - logs:/var/www/logs
